- name: 70-add-env-variables
  hosts: localhost
  vars:
          config_variables: azconfig.yml
          config_mount_point: /mnt

  vars_files:
          - "{{ config_mount_point + '/' + config_variables }}"

  tasks:
    - name: Add env variables in the bashrc file
      lineinfile:
        path: /root/.bashrc
        line: export {{item.name}}={{sap_hostname}}
      when: item.name == 'HOST'
      with_items:
        - {name: 'HOST'}
    - name: Execute the bashrc script
      shell: source /root/.bashrc